export { default as Form } from './components/form.bak1'
// export { default as Form.Item } from './components/form-item'
export { default as Input } from './components/input'
export { default as InputNumber } from './components/input-number'
export { default as Checkbox } from './components/checkbox'
export { default as Radio } from './components/radio'
export { default as TextArea } from './components/textarea'
export { default as Select } from './components/select'
export { default as Slider } from './components/slider'
export { default as Switch } from './components/switch'
export { default as Button } from './components/button'
// export { default as Icon } from './components/icon';
export * from './components/Row'
